name: Release Artifacts

on: 
  push:
    branches:
      - master

jobs:
  release:
    name: Release Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install requirements
        run: |
          pip install wheel
          pip install twine
      - name: Compile Linux wheel
        run: |
          python setup.py sdist bdist_wheel
      - name: Get Version
        run: |  
          run: echo "version=$(grep -Po 'version="(.+?)"' setup.py) && version="${version:9}" && version="${version::-1}" >>$GITHUB_OUTPUT
        id: version
      - name: Create Release
        uses: softprops/action-gh-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          name: v.${{ steps.version.outputs.version }}
          tag_name: v.${{ steps.version.outputs.version }}
          body_path: .github/Changelog.md
          files: |
            ./artifact-wheel/cnl2feedcrawler-${{ steps.version.outputs.version }}-py3-none-any.whl
            ./artifact-exe/cnl2feedcrawler-${{ steps.version.outputs.version }}-standalone-win64.exe
          fail_on_unmatched_files: true
      - name: Upload to PyPI
        run: |
          python -m twine upload ./dist/* -u __token__ -p ${{ secrets.PYPI_TOKEN }}


