name: Release Artifacts

on: 
  push:
    branches:
      - main

jobs:
  release:
    name: Release Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install requirements
        run: |
          pip install wheel
          pip install twine
      - name: Compile Linux wheel
        run: |
          python setup.py sdist bdist_wheel
      - name: Get Version
        run: echo "version=$(python setup.py --version)" >>$GITHUB_OUTPUT
        id: version
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./dist/*.whl"
          artifactErrorsFailBuild: true
          bodyFile: ".github/Changelog.md"
          tag: v.${{ steps.version.outputs.version }}
      - name: Upload to PyPI
        run: |
          python -m twine upload ./dist/* -u __token__ -p ${{ secrets.PYPI_TOKEN }}


